# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 01:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField(verbose_name='学号')),
                ('stu_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('stu_class', models.CharField(max_length=50, verbose_name='班级')),
                ('apply_type', models.CharField(max_length=10, verbose_name='测评类型')),
                ('apply_year', models.CharField(max_length=30, verbose_name='评测学年')),
                ('is_add_score', models.BooleanField(default=True, verbose_name='是否是加分')),
                ('activity', models.CharField(blank=True, max_length=500)),
                ('score', models.IntegerField(verbose_name='加分数值')),
                ('image', models.ImageField(max_length=200, null=True, upload_to='image', verbose_name='证明材料照片')),
                ('examine_date', models.DateField(auto_now=True, verbose_name='审批日期')),
                ('examine_status', models.CharField(max_length=10, verbose_name='审批状态')),
                ('examine_content', models.CharField(max_length=200, null=True, verbose_name='审批意见')),
                ('is_examined', models.BooleanField(default=False, verbose_name='是否已经审批')),
                ('is_upload', models.BooleanField(default=False, verbose_name='是否已经上传数据到网站')),
            ],
        ),
        migrations.CreateModel(
            name='BonusCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=80, verbose_name='加分内容')),
                ('limit', models.CharField(max_length=15, verbose_name='加分限制')),
                ('Bonus_type', models.CharField(max_length=10, verbose_name='加分类型:德育/智育')),
            ],
        ),
        migrations.CreateModel(
            name='BonusDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(max_length=80, null=True, verbose_name='选项内容')),
                ('score', models.FloatField(verbose_name='分值')),
                ('is_changeable', models.BooleanField(default=False, verbose_name='是否可编辑')),
                ('min_score', models.FloatField(null=True, verbose_name='可编辑最低分')),
                ('max_score', models.FloatField(null=True, verbose_name='可编辑最高分')),
                ('Bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.BonusCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='cookie名')),
                ('value', models.CharField(max_length=500, verbose_name='cookie值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.AddField(
            model_name='apply',
            name='bonus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.BonusDetail', verbose_name='加分类别'),
        ),
    ]
