# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuscategory',
            name='score',
            field=models.FloatField(null=True, verbose_name='默认分值'),
        ),
    ]
