# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20170920_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='big_credit',
            field=models.CharField(max_length=10, null=True, verbose_name='加分项最高分'),
        ),
        migrations.AddField(
            model_name='apply',
            name='small_credit',
            field=models.CharField(max_length=10, null=True, verbose_name='加分项最低分'),
        ),
        migrations.AddField(
            model_name='bonuscategory',
            name='is_changeable',
            field=models.BooleanField(default=False, verbose_name='分数是否可改'),
        ),
    ]
