# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20170920_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookies',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
