# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20170920_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='bonus_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.BonusCategory', verbose_name='加分总类别'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='bonus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.BonusDetail', verbose_name='加分详细类别'),
        ),
    ]
