# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20170921_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='apply_url',
            field=models.CharField(max_length=500, null=True, verbose_name='详情页链接'),
        ),
    ]
