# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_apply_apply_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='add_score',
            field=models.FloatField(null=True, verbose_name='申请加分数'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='score',
            field=models.FloatField(verbose_name='加分填写数值'),
        ),
    ]
