# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_auto_20170921_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='申请的id'),
        ),
    ]
