# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_auto_20170921_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_id',
            field=models.IntegerField(null=True, verbose_name='申请的id'),
        ),
        migrations.RemoveField(
            model_name='apply',
            name='object_id',
        ),
        migrations.AlterUniqueTogether(
            name='apply',
            unique_together=set([('apply_id', 'stu_id')]),
        ),
    ]
