# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_auto_20170921_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuscategory',
            name='max_score',
            field=models.FloatField(null=True, verbose_name='最高分'),
        ),
        migrations.AddField(
            model_name='bonuscategory',
            name='min_score',
            field=models.FloatField(null=True, verbose_name='最低分'),
        ),
    ]
