# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_auto_20170922_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonusdetail',
            old_name='Bonus',
            new_name='bonus_category_id',
        ),
    ]
