# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-27 01:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_auto_20170922_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='学工网账号')),
                ('password', models.CharField(max_length=50, verbose_name='学工网密码')),
                ('is_now_use', models.BooleanField(default=False, verbose_name='现在登录的用户')),
                ('last_login', models.DateTimeField(default=datetime.datetime.now, verbose_name='上次登录时间')),
            ],
        ),
        migrations.AlterField(
            model_name='apply',
            name='examine_status',
            field=models.CharField(default='等待审批', max_length=10, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='apply',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operation.UserAccount', verbose_name='账号'),
            preserve_default=False,
        ),
    ]
